### ISSUE TITLE
should loadEnts return null for ids which aren't loadable?

### ISSUE THREAD

**Issue by lolopinto** [lolopinto/ent#1070]
loadEnts

**Comment by Swahvay** [comment]
What is an unloadable ID? Is this a privacy thing?

**Comment by lolopinto** [comment]
privacy or data not fetchable

since `Foo.loadMany()` returns a map, seems like it should return that id too. currently doesn't but was changing the code and it seemed like it did

`loadEntsList` which you have to call manually returns a list not a map and that makes sense to not return the ids.

**Comment by Swahvay** [comment]
I guess the one advantage to not doing this, is that you could type the Map without nulls. Since you could always just do `ents[id]` either way, I might prefer to be able to do `Object.values(ents)` and not have to do null checks afterwards.
