### ISSUE TITLE
Codegen error when using PasswordType in tutorial

### ISSUE THREAD

**Issue by matt-kodex** [lolopinto/ent#1163]
When running `npm run codegen` after adding the user schema from the tutorial with ent-starter, the following error occurs:
```
> docker-compose -f docker-compose.dev.yml run --rm app tsent codegen

Creating ent-starter ... done
Error:
  we require 1 primary key for each table. schemas had 0
Usage:
  tsent [command]
```
I have the following dependencies in package.json
```
  "dependencies": {
    "@snowtop/ent": "^0.1.0-alpha91",
    "@snowtop/ent-email": "^0.1.0-alpha1",
    "@snowtop/ent-password": "^0.1.0-alpha1",
    "@snowtop/ent-phonenumber": "^0.1.0-alpha1",
    "@types/express": "^4.17.9",
    "better-sqlite3": "^7.5.3",
    "express": "^4.17.1",
    "express-graphql": "^0.12.0",
    "graphql": "^16.5.0",
    "graphql-helix": "^1.12.0",
    "jest": "^29.1.2"
  }
```

**Comment by lolopinto** [comment]
hi, what files do you have?

**Comment by matt-kodex** [comment]
Looks like when I ran codegen, it added schema.py - which matches the error.  
```
~/code/ent-starter/src/schema on main [+!] $ ls
__pycache__    schema.py      user_schema.ts versions
```

From where should I be running `npm run codegen`?

**Comment by lolopinto** [comment]
hmm, all that seems fine. you should be running it from the root of your application e.g. in `~/code/ent-starter`. are you running it there or in `src/schema`?

**Comment by lolopinto** [comment]
the other thing i can think of is, do you mind showing me what your user_schema.ts looks like?

**Comment by matt-kodex** [comment]
```
import { EntSchema, StringType } from "@snowtop/ent";
import { EmailType } from "@snowtop/ent-email";
import { PasswordType } from "@snowtop/ent-password";

const UserSchema = new EntSchema({
  fields: {
    firstName: StringType(),
    lastName: StringType(),
    emailAddress: EmailType({ unique: true  }),
    password: PasswordType(),
  },
});
export default UserSchema;
```

**Comment by matt-kodex** [comment]
When I comment out line 10, codegen works fine.

**Comment by lolopinto** [comment]
ok, weird. thanks for answering all my questions. will take a look

**Comment by lolopinto** [comment]
I think the issue is the wrong docker image. I need to update ent-starter:main to point to the right image.

can you change the first line`develop.Dockerfile` to 

`FROM ghcr.io/lolopinto/ent:0.1.0-alpha.28-nodejs-17-dev`

**Comment by matt-kodex** [comment]
Awesome, seems to have worked!  Added to the DB, but have a new error now:
```
~/code/ent-starter on initial_schema $ npm run codegen

> ent-starter@1.0.0 codegen
> docker-compose -f docker-compose.dev.yml run --rm app tsent codegen
You're adding a new field 'password' to an existing Node 'User' which isn't nullable. This could result in database errors. Are you sure you want to do that? Y/N: Y
Error:
  auto_schema error: Can't locate revision identified by 'd96ebc42b8c7'
```

**Comment by lolopinto** [comment]
my guess is you deleted a previous schema file when you were trying to figure stuff out. did you delete a file from `src/schema/versions/`? or delete the entire folder previously?

https://github.com/lolopinto/ent/issues/999 exists to help with debugging missing hashes e.g. after deletion. plan to work on that soon 

`rm -rf .ent` and wipe your db to start again since early in your explorations

**Comment by matt-kodex** [comment]
Sounds good.  I'll take a look there.  Thank you for your help!

**Comment by matt-kodex** [comment]
FYI I use `git commit --amend` a lot, guessing that messed up the identified revision ...

**Comment by lolopinto** [comment]
maybe...

it shouldn't since the revisions are stored on disk. 

the underlying database migration system is https://alembic.sqlalchemy.org/en/latest/ 

```
ls src/schema/versions 
# shows the list of revision files and the prefixes {revision_...*.py} 
```
