### ISSUE TITLE
No ability to increment / update a value on the same object multiple times

### ISSUE THREAD

**Issue by rvlasveld** [lolopinto/ent#1261]
_I believe that the following isn't currently possible, but I might also miss something from the API / documentation._

I'm trying to run multiple triggers in a single transaction, where each trigger updates/increments the same value multiple times. A typical use case of this would be accounting: we have an account with a balance and create multiple transactions, each with an amount. 

Each transaction should update the account's balance accordingly such that the final balance is the sum of the original balance and the transaction amounts. 

When this is done asynchronously, or in parallel, the balance isn't updated correctly since all trigger use the account state as at the start of the transaction. 

I have logic as such:

```typescript
// In create_transaction_action.ts 
getTriggers(): CreateTransactionActionTriggers {
  return [{
    async changeset(builder, input) {
      const { amount } = input;
      
      const account = await Account.loadX(builder.viewer, input.accountID);
      
      return UpdateAccountBalanceAction.create(builder.viewer, account, {
        amount,
        sign,
      }).changeset();
    },
  }];
}

// In update_account_balance_action.ts
getTriggers(): UpdateAccountBalanceActionTriggers {
  return [{
    async changeset(builder, input) {
      builder.updateInput({
        balance: builder.existingEnt.balance + input.amount,
      });
    },
  }];
}
```

Example usage:

```typescript
const account = await Account.loadX(vc, accountID);
console.log("Balance before:", account.balance); // e.g. 100

const transactions: Array<Promise<Transaction>> = [];

transactions.push(CreateTransactionAction.create(vc, {accountID, amount: 30}).saveX());
transactions.push(CreateTransactionAction.create(vc, {accountID, amount: 50}).saveX());

// Create Transaction asynchronously - this is important. 
await Promise.all(transactions);

// Reload the account
const account = await Account.loadX(vc, accountID);
console.log("Balance before:", account.balance); // e.g. 130 - should be 180
```

It seems that the `account` object isn't reloaded from the DB in between the `CreateTransactionAction` calls (and downstream triggers). I've also tried the use `BaseAction.bulkAction()`, and using Observers instead of Triggers, but it had the same effect.

**Comment by lolopinto** [comment]
I think you're right that this isn't possible. Will think about it and see if there's a good way to support this

**Comment by lolopinto** [comment]
fixed in latest
