### ISSUE TITLE
Field arguments are not forwarded correctly

### ISSUE THREAD

**Issue by rvlasveld** [lolopinto/ent#1281]
The generated code for arguments in a field seems to be incorrect; it's probably missing the `args.` prefix. 

My field (on `user.ts`):

```typescript
export class User extends UserBase {
  ...

  @gqlField({type: "[Transaction]"})
    recentTransactions(
      @gqlArg("count", {type: GraphQLInt}) count: number,
    ): Transaction[] {
      console.log("recentTransactions, user is this:", this, count);
      return [];
    }
}
```

The generated code, in `user_types.ts` (annotated to highlight the issue): 

```typescript
...
    recentTransactions: {
      type: new GraphQLNonNull(
        new GraphQLList(new GraphQLNonNull(TransactionType)),
      ),
      args: {
        count: {
          description: "",
          type: new GraphQLNonNull(GraphQLInt),
        },
      },
      resolve: (user: User, args: any, context: RequestContext<Viewer>) => {
        return user.recentTransactions(count); // <--- ERROR: Cannot find name 'count'
      },
    },
```

It seems that the call to the original TS method should prefix the arguments with `args.`, instead of using them directly. 

This does work correctly for mutations and queries, and I believe that fields should also support arguments. I'm also happy to contribute to this project, but I would need a hint on where this generation is done (e.g. how it's prefixed for mutations/queries)

**Comment by lolopinto** [comment]
fixed in latest
