### ISSUE TITLE
TypeScript 5.0 and decorators

### ISSUE THREAD

**Issue by lolopinto** [lolopinto/ent#1392]
seems promising https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#decorators

**Comment by Swahvay** [comment]
Should I subscribe to this task to know when I can safely update to TS5?

**Comment by lolopinto** [comment]
my guess is you can update to TS5 and be fine but I've not looked into it.

The new decorator API seemed promising enough that I could change how custom graphql worked and make TS 5 a requirement at some point...
