### ISSUE TITLE
DateType schema field generates GraphQL type that isn't provided

### ISSUE THREAD

**Issue by Swahvay** [lolopinto/ent#1648]
Using the `DateType` schema field type generates a GraphQL type of `Time`, but that object is never defined in the schema file.

```js
// foo_schema.ts
const FooSchema = new EntSchema({
  date: DateType({});
}
```

```graphql
# schema.gql
type Foo implements Node {
  date: Time!
}
```

**Comment by lolopinto** [comment]
there's no `scalar Time` line in `schema.gql`?

maybe it somehow is only added if there's a `TimestampType` type and whatever logic does it doesn't account for `DateType`. not that big a deal since the `schema.gql` file is only informative but we should fix to avoid confusion.

**Comment by Swahvay** [comment]
> there's no scalar Time line in schema.gql?

Nope.

> not that big a deal since the `schema.gql` file is only informative

What do you mean by this? I'm using this as my schema definition for a relay app. Is that not the right way to do it?

**Comment by lolopinto** [comment]
>What do you mean by this? I'm using this as my schema definition for a relay app. Is that not the right way to do it?

it's almost certainly right. i just haven't focused on it to be 100% accurate and it's not tested. 

usually, i've used it just to spotcheck the schema and then use a tool like `get-graphql-schema` for relay since that's presumably tested and using the generated GraphQLSchema to derive it.

**Comment by Swahvay** [comment]
> usually, i've used it just to spotcheck the schema and then use a tool like get-graphql-schema for relay since that's presumably tested and using the generated GraphQLSchema to derive it.

I guess I don't follow. Why generate this file, then spot check it against another library that generates the file? Why not just have the ent library call `get-graph-schema` to generate the file?

**Comment by lolopinto** [comment]
hmm, it's more like i generate it and then when i make schema changes, i look at this file to see that the changes are what I think they should be

I used to use `graphql-js` to generate this file but it was slowing down codegen because i had to load node so I switched to [generating manually](https://github.com/lolopinto/ent/pull/648)

**Comment by lolopinto** [comment]
i had https://github.com/lolopinto/ent/pull/651 a while back to sanitize/as my test but for some reason i abandoned it. would  need to redo something like that

**Comment by Swahvay** [comment]
Hmm, yeah, generating the graphQL does include the `scalar Time`, but it re-arranges everything so there's basically no way to tell if there were other changes as well. Maybe this could be done as part of a `yarn codegen --full` or something? That way you would've have to worry about doing it yourself perfectly.

**Comment by lolopinto** [comment]
what were you doing that it wasn't generating the graphql? I had been trying to repro and I couldn't so good to know that it works now

**Comment by Swahvay** [comment]
It was generating the graphQL when I ran `yarn codegen`, but was missing the `scalar Time` piece. Running `get-graph-schema` pointed to my local server generates the schema with the missing `Time` piece.

**Comment by lolopinto** [comment]
oh, so `yarn codegen` still not generating it?

**Comment by Swahvay** [comment]
It's generating the `schema.gql` file, yes, just not the one line, which caused it to error.

**Comment by Swahvay** [comment]
This seems to be working now.
