### ISSUE TITLE
Add option to toggle default export for generated actions

### ISSUE THREAD

**Issue by Swahvay** [lolopinto/ent#1686]
`ent/foo/actions/add_foo.ts` has `export default class AddFoo { ... }`, but to expose all actions in the package for export makes automating the index.ts file hard with these default exports.

**Comment by Swahvay** [comment]
This is actually a fairly important one as it blocks me from updating my schema and re-running codegen without a lot of extra work. I had to manually adjust the imports of generated files so it's a little bit of a pain to do that each time I make changes.

**Comment by lolopinto** [comment]
testing a new image @ https://github.com/lolopinto/ent/pull/1688. will check to see if the build worked in the morning 

after, here are the steps to test it
* update `ent.yml` and add this line under `codegen`: https://github.com/lolopinto/ent/blob/configure-imports/examples/todo-sqlite/ent.yml#L14
* `npm run codegen`
* `docker-compose -f docker-compose.dev.yml run --rm app tsent run_script  src/scripts/fix_action_exports.ts` to fix the export for the actions themselves
* fix the rest of the imports in other places e.g. tests and other actions which call them in changesets

**Comment by Swahvay** [comment]
So, a few things from that list. 1, I had to run `rebuild-image`, and 2`, I got an error running `run_script`

```
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module './fix_action_exports.js'
```

But it didn't matter because it worked after the codegen anyways.
