### ISSUE TITLE
Optional action only fields of type "Object" in an edit action don't optional-ize their nested fields

### ISSUE THREAD

**Issue by Swahvay** [lolopinto/ent#1706]
If I have an action:

```js

{
  operation: ActionOperation.Edit,
  actionName: 'SomeUpdateAction',
  inputName: 'SomeUpdateInput',
  hideFromGraphQL: true,
  actionOnlyFields: [
    {
      name: 'fooObject',
      type: 'Object',
      nullable: true,
      actionName: 'OtherObjectUpdateAction',
    },
  ],
},
```

If `OtherObject` includes non-nullable fields in the schema, even if they are optional in `OtherObjectUpdateAction`, they are not optional in `SomeUpdateInput.fooObject`.

**Comment by Swahvay** [comment]
Still seeing this with the latest image. I noticed in your commit that you used `CreateTagAction` as your action. I'm using an edit action as my actionOnlyField, if that makes any difference.

**Comment by lolopinto** [comment]
hmm must never have tested that. it's the same underlying issue i think. will take a look later tonight.
