### ISSUE TITLE
Optional StructTypeAsList field errors if passed an empty array on action

### ISSUE THREAD

**Issue by Swahvay** [lolopinto/ent#1730]
If a `StructTypeAsList` field is optional, and an empty array is passed as the value for (at least) a create action, an error is thrown: `TypeError: input.map is not a function`. Passing in `undefined` works as expected.

**Comment by Swahvay** [comment]
Actually I think this is a larger problem. It's the same global type field that's causing problems for me on another ent, but this time with data.

```js
contacts: StructTypeAsList({
  tsType: 'ContactInfo',
  nullable: true,
  fields: {
    name: TextType({
      maxLen: 200,
    }),
    userID: UUIDType({
      nullable: true,
      foreignKey: { schema: 'User', column: 'ID' },
    }),
    phone: PhoneNumberType({
      nullable: true,
    }),
    email: EmailType({
      nullable: true,
    }),
    contactType: TextType({
      maxLen: 200,
      nullable: true,
    }),
  },
}),
```

If I pass any data it fails with the same error. Interestingly though, I have another `StructTypeAsList` field on the ent itself that doesn't cause the error.

```js
officials: StructTypeAsList({
  tsType: 'CompetitionOfficial',
  nullable: true,
  fields: {
    name: TextType({
      maxLen: 200,
    }),
    userID: UUIDType({
      nullable: true,
      foreignKey: { schema: 'User', column: 'ID' },
    }),
    license: TextType({
      maxLen: 200,
      nullable: true,
    }),
  },
}),
```

(`TextType` is basically just `StringType` with some built in functionality like strip emojis etc.). Passing in `officials` works, but `contacts` doesn't. With `undefined` values or not. I'll keep investigating, but the error is stemming from `orchestrator.build`.

**Comment by lolopinto** [comment]
I just tried the first part with a simple type and it worked.

for the second part, are they both globalTypes?

**Comment by Swahvay** [comment]
Only the ContactInfo one is a global type, the one that's erroring, the other one is just on the ent and works fine.
