### ISSUE TITLE
UpdateOperation data Map does not include actionOnlyFields

### ISSUE THREAD

**Issue by Swahvay** [lolopinto/ent#1764]
When using `transformWrite`, the `data` Map only includes fields defined on the schema. Obvious work around is to just use the `input` object.

**Comment by lolopinto** [comment]
i think this one is by design/wontfix

https://github.com/lolopinto/ent/blob/0b14f75ca8f10bca63ef42cfc6ed99bf39566d7f/ts/src/schema/schema.ts#L320-L330

```
// input. same input that's passed to Triggers, Observers, Validators. includes action-only fields 
   input: Data; 
   // data that'll be saved in the db 
```

maybe we need better documentation for this?

**Comment by Swahvay** [comment]
That's fine if it's by design. When would `data` ever be more than a subset of `input`? Does `data` include triggers or field formatters or something?

**Comment by lolopinto** [comment]
it includes default value for fields, formatted fields etc

what would be written to the database

**Comment by Swahvay** [comment]
Gotchya. Feel free to close/change this to an add documentation ticket/whatever you want. 👍
