### ISSUE TITLE
CustomClauseQuery without a required clause?

### ISSUE THREAD

**Issue by ashleyxue529** [lolopinto/ent#1769]
I'm trying to query for all objects in my db for a graphql connection, is there some no-op clause I could use? Or is there another query I should use?

RIght now I'm using:
```
    return new CustomClauseQuery(omniVC, {
      loadEntOptions: Object.loaderOptions(),
      clause: <what do i put here>?
      name: "objects_connection",
      orderby: [
        {
          column: "created_at",
          direction: "DESC",
        },
      ],
    });
```

**Comment by Swahvay** [comment]
You could use `Expression('1 = 1')`.

**Comment by Swahvay** [comment]
Or `query.NotEq('id', null)`.

**Comment by ashleyxue529** [comment]
aha yes! was looking for something like `Expression`, thank you :)

**Comment by lolopinto** [comment]
i intentionally didn't make it easy to do table scans but yah `Expression` works here

The other thing you can do is `Foo.loadCustom('select * from blah')` but you don't get a connection for that only a list
