### ISSUE TITLE
Couple minor errors with pattern generation

### ISSUE THREAD

**Issue by Swahvay** [lolopinto/ent#1792]
Two minor things.

1) The mixin interface doesn't default to the Viewer specified in `ent.yml`:

```js
export interface ISomePattern<TViewer extends Viewer = Viewer>
  extends ISomePatternBase<TViewer>
```
should be

```js
export interface ISomePattern<TViewer extends MyCustomViewer = MyCustomViewer>
  extends ISomePatternBase<TViewer>
```
(The base should also be `ISomePatternBase<TViewer extends MyCustomViewer = MyCustomViewer>`.)

2) Field edges and foreign keys loaders do not get defined on pattern interfaces. Edges defined on the pattern generate `queryFoo` interfaces correctly, but `fieldEdge`s or `foreignKey`s defined on a field in a pattern do not generate the `loadFoo` or `queryFoo` method definitions on the interface.

**Comment by lolopinto** [comment]
for 2, looks like i decided to go from the other direction since it would have been a 1/1 mapping in the case of the fieldEdge and foreignKey?

probably because i didn't think it was worth it, not sure?

**Comment by lolopinto** [comment]
for 1/, fixed in https://github.com/lolopinto/ent/pull/1800

non-base classes would have to be fixed manually.

**Comment by lolopinto** [comment]
I just realized I completely misunderstood #2. 🤦🏿‍♂️

**Comment by Swahvay** [comment]
> for 1/, fixed in https://github.com/lolopinto/ent/pull/1800
> 
> non-base classes would have to be fixed manually.

No problem! Thanks for getting to this. 🙂
