### ISSUE TITLE
CustomClauseQueries don't work correctly on ent fields

### ISSUE THREAD

**Issue by Swahvay** [lolopinto/ent#1836]
CustomClauseQuery doesn't expect to have source ents because it's original use was only on the root resolver. Following #1768 it was added to Ents, but the source was never accounted for. The source ent is used as a key into the map of edges (so if you have two ents fetching edges it knows which edges set goes with which ent). The offending line is here: https://github.com/lolopinto/ent/blob/main/ts/src/core/query/custom_clause_query.ts#L186 which just hardcodes `1` as the source ID.

**Comment by Swahvay** [comment]
The tough part here is that `BaseEdgeQuery` has an abstract method `sourceEnt(id: ID): Promise<Ent | null>`. `CustomClauseQuery` just always returns `null`, but you need to call the static method on the source instance's class. What if we added a new property to `Ent` that was just a reference to its own class?

```ts
class UserBase implements Ent {
  public entClass = UserBase;
}
```

Then `CustomClauseQuery` (or whatever) could just do:
```ts
sourceEnt(id: ID): Promise<Ent | null> {
  return this.source?.entClass.load(this.source.viewer, this.source.id);
}
```

**Comment by Swahvay** [comment]
A more detailed explanation of the problem:

1) Give an ent `Horse`, there exists this method on it:
```ts
@gqlField({
  class: 'Horse',
  name: 'offspring',
  type: gqlConnection('Horse'),
})
offspring(): CustomClauseQuery<Horse> {
  return new CustomClauseQuery(this.viewer, {
    loadEntOptions: Horse.loaderOptions(),
    clause: query.Or(
      query.Eq('sire_id', this.id),
      query.Eq('dam_id', this.id),
    ),
    name: 'getOffspring',
  });
}
```

2) Codegen generated this in the GraphQL `horse_type.ts`:
```ts
export const HorseType = new GraphQLObjectType({
  name: 'Horse',
  fields: (): GraphQLFieldConfigMap<Horse, RequestContext> => ({
    offspring: {
      type: new GraphQLNonNull(HorseToOffspringConnectionType()),
      resolve: (
        obj: Horse,
        args: any,
        context: RequestContext,
      ) => {
        return new GraphQLEdgeConnection(
          obj.viewer,
          obj, // <-- Notice that the Horse object is being set as the "source"
          (v, obj: Horse) => obj.offspring(),
          args,
        );
      },
    },
  }),
  interfaces: () => [GraphQLNodeInterface],
  isTypeOf(obj) {
    return obj instanceof Horse;
  },
});
```

3) Inside `GraphQLEdgeConnection`, when a source is provided, it uses the source ID to get the correct page info for graphQL connections/pagination 

[edge_connection.ts#L139](https://github.com/lolopinto/ent/blob/main/ts/src/graphql/query/edge_connection.ts#L139):
```ts
async queryPageInfo(): Promise<PaginationInfo> {
  await this.queryData();
  const paginationInfo = (await this.query).paginationInfo(); // *A
  if (this.source !== undefined) {
    return paginationInfo.get(this.source.id) || this.defaultPageInfo(); // *B
  }
  if (paginationInfo.size > 1) { // *C
    throw new Error(`Query mas more than one item yet no source was given`);
  }
  for (const [_, value] of paginationInfo) { // *D
    return value;
  }
  return this.defaultPageInfo();
}
```
Some things to note above:

>   **A)** It's getting the paginationInfo from the query (this is a `BaseEdgeQuery` instance – so that includes `CustomClauseQuery` as well as generated `CustomEdgeQueryBase`-extended instances).
>   **B)** Because `this.source` was set to the `Horse` object from the `HorseType` graphQL object, it will try to get the pagination for this specific horse edge. It will never find it (I'll show why later), so it always falls back to the default which won't include cursor information and makes it impossible to paginate.
>   **C)** This is where it checks that if you didn't pass in a source, there is only one possible pagination object (this is something that is hard coded into `CustomClauseQuery`)
>   **D)** And this is where it gets that one pagination object and returns it.

 
4) Normally, for generated edge queries on ents, it generates something like this, extending `CustomEdgeQueryBase` (instead of the `CustomClauseQuery` I returned from the `offspring` method above):
```ts
export class HorseToSireOfQueryBase<
  TEnt extends Horse = Horse,
> extends CustomEdgeQueryBase<TEnt, Horse> {
  constructor(
    viewer: Viewer,
    src: TEnt | ID,
    sortColumn?: string | OrderBy,
  ) {
    super(viewer, {
      src: src, // Notice here that it's passing the source
      groupCol: 'sire_id',
      loadEntOptions: Horse.loaderOptions(),
      name: 'HorseToSireOfQuery',
      sortColumn: typeof sortColumn === 'string' ? sortColumn : undefined,
      orderby: typeof sortColumn === 'string' ? undefined : sortColumn,
    });
  }

  async sourceEnt(id: ID) {
    return Horse.load(this.viewer, id);
  }
}
```

5) And so finally, when you call `loadRawData` from inside these queries (this method that does the actual fetching), `CustomEdgeQueryBase` instances correctly cache the results with the source's ID value as the map key: [custom_query.ts#L291](https://github.com/lolopinto/ent/blob/main/ts/src/core/query/custom_query.ts#L291) whereas `CustomClauseQuery` has no reference to the source object and so defaults the cache to a map with just a single `1` key: [custom_clause_query.ts#L186](https://github.com/lolopinto/ent/blob/main/ts/src/core/query/custom_clause_query.ts#L186). This is why step 3B above always fails. The `this.source` object is always set in the `GraphQLEdgeConnection` object, but never in the underlying `CustomClauseQuery`.

**Comment by lolopinto** [comment]
what do you think of https://github.com/lolopinto/ent/pull/1837?
