### ISSUE TITLE
Feature Request: defaultToViewer field option

### ISSUE THREAD

**Issue by mrtom** [lolopinto/ent#435]
I think it would be valuable to specify that a field on an ent should default to the viewer.

For example, imaging a task app where a task has the following fields:

```
    StringType({ name: "title" }),
    StringType({ name: "body" }),
    BooleanType({ name: "closed", nullable: false, defaultValueOnCreate: () => false }),
    UUIDType({
      name: "authorID",
      fieldEdge: { schema: "User", inverseEdge: "authoredTasks" },
      storageKey: "user_id",
    }),
```

or similar.

We would want to set the actions like this:

```
actions: Action[] = [
    {
      operation: ActionOperation.Create,
      fields: ["title", "body", "authorID"],
    },
    {
      operation: ActionOperation.Edit,
    },
    {
      operation: ActionOperation.Delete,
    },
    // Set closed / open
    {
      operation: ActionOperation.Edit,
      actionName: "EditTaskClosedAction",
      graphQLName: "taskClosedEdit",
      inputName: "EditTaskClosedInput",
      fields: [requiredField("closed")],
    },
  ];
```

such that the create action doesn't have to send a value for `closed` - tasks are created opened by default.

This will create a gql create mutation with the following input:

```
input TaskCreateInput {
  title: String!
  body: String!
  authorID: ID!
}
```

However, in the vast majority of cases we likely want the `authorID` to be set to that of the viewer. We can enforce that with privacy rules (I think, haven't tried?), but that still leaves the API with a unnecessary field for the common case.

I'd rather default to having the `authorID` missing from the `TaskCreateInput` entirely (but I can see why that would probably require a second mutation to exist that allows you to set the `authorID`, perhaps for admin interface etc.

So perhaps a good compromise is to make the `authorID` optional in the input, and when missing default to the ID of the viewer. And add a field option `defaultToViewer`, which by default sets the field to the UUID of the viewer if it's missing?

i.e. the schema would change to:

```
    StringType({ name: "title" }),
    StringType({ name: "body" }),
    BooleanType({ name: "closed", nullable: false, defaultValueOnCreate: () => false }),
    UUIDType({
      name: "authorID",
      fieldEdge: { schema: "User", inverseEdge: "authoredTasks" },
      storageKey: "user_id",
      defaultToViewer: true,
    }),
```

and the input would change to:

```
input TaskCreateInput {
  title: String!
  body: String!
  authorID: ID
}
```

And clients, by default, would ignore the `authorID` field entirely.

**Comment by lolopinto** [comment]
oh, and your actions will change to:

```ts
actions: Action[] = [
    {
      operation: ActionOperation.Create,
      fields: ["title", "body"],
    },
    {
      operation: ActionOperation.Edit,
    },
    {
      operation: ActionOperation.Delete,
    },
    // Set closed / open
    {
      operation: ActionOperation.Edit,
      actionName: "EditTaskClosedAction",
      graphQLName: "taskClosedEdit",
      inputName: "EditTaskClosedInput",
      fields: [requiredField("closed")],
    },
  ];
```

so you'll still have the authorID missing from the generated input

**Comment by lolopinto** [comment]
ok, i've implemented the `defaultValueOnCreate` method.

Not trivial to implement `defaultToViewer` which basically does what you want.

few questions:

* my guess is  `defaultToViewer` should only apply during creation and not editing? If so, should be renamed to something that makes that clear.
* my instinct is to throw if both `defaultToViewer(OnCreate)` and `defaultValueOnCreate` exist since they'd be doing the same thing. does that align with what you'd expect?

**Comment by mrtom** [comment]
I think generalising `defaultValueOnCreate` makes loads of sense!

Do I think `defaultToViewer` is valuable still - probably, but only if the API isn't overly complicated because of it. I guess maybe implement and I'll play with it if it's trivial?

> my guess is `defaultToViewer` should only apply during creation and not while editing?

Yes I think so too. If a task was created by Alice, and later edited by Bob (who's an admin) then the omission of an `authorID` field in the edit payload shouldn't overwrite the task to be authored by Bob. I can't think of any case where I'd expect the author to be updated in that case.

> If so, should be renamed to something that makes that clear.

`defaultToViewerOnCreate`?

> my instinct is to throw if both `defaultToViewer(OnCreate)` and `defaultValueOnCreate` exist since they could be doing conflicting things. does that align with what you'd expect?

Yes. Although this is where I wonder if your more general approach is enough and we should just can `defaultToViewer` - it's adding extra weight to the API that could be solved easily enough in documentation. But it *is* also cleaner and is likely to be a common use case. So I'm conflicted.

But coming down on implementing as it should be nice and clean for the common use case.

**Comment by lolopinto** [comment]
in newest version

**Comment by mrtom** [comment]
Amazing. I'll upgrade and check it out.

**Comment by mrtom** [comment]
Works a treat, love it 👍
