### ISSUE TITLE
ability to disable base64 encoding in graphql id 

### ISSUE THREAD

**Issue by lolopinto** [lolopinto/ent#468]
right now every graphql object has an id that's base 64 encoded. may not always want that if you have an existing API to integrate to or just disagree with the overhead of base 64 encoding

https://github.com/lolopinto/ent/pull/186 and https://github.com/lolopinto/ent/pull/190 relevant

**Comment by zrait** [comment]
https://www.postgresql.org/docs/9.1/datatype-uuid.html
