### ISSUE TITLE
custom Node names + schema/Node clash

### ISSUE THREAD

**Issue by lolopinto** [lolopinto/ent#591]
either change default Ent from `Foo` to `EntFoo` or provide ability to customize it with regex or something. VSCode issues with collision with schema name

GraphqlName should remain as `Foo`

or change Schema names to `FooSchema` and keep name

**Comment by Swahvay** [comment]
My 2¢/personal preference is to rename to `FooSchema`, less change and keeps the `Ent` out of normal everyday code.
