### ISSUE TITLE
Use Referenced Ent Type in AssocEdgeGroup status functions

### ISSUE THREAD

**Issue by Swahvay** [lolopinto/ent#608]
Given the following `AssocEdgeGroup` between a `Barn` and a `Horse`; referencing the boarding status and/or permission to become or request to become a boarder (and defined in `Barn`'s schema):

```javascript
{
  name: 'Boarders',
  groupStatusName: 'BoardingStatus',
  nullStates: ['canBoard', 'canRequestBoard', 'cannotRequestBoard'],
  nullStateFn: 'boardingStatus',
  assocEdges: [
    {
      name: 'Boarding',
      schemaName: 'Horse',
      inverseEdge: { name: 'BoardingWith' },
    },
    {
      name: 'BoardingRequested',
      schemaName: 'Horse',
      inverseEdge: { name: 'BoardingRequestedWith' },
    },
  ],
}
```

The generated functions in `BarnBase` include:

```typescript
// this should be overwritten by subclasses as needed.
protected async boardingStatus() {
  return BarnBoardingStatus.CanBoard;
}
async viewerBoardingStatus(): Promise<BarnBoardingStatus> {
  // ...
}
```

But the purpose of the edge is to get a relationship between the horse and barn, not the user and barn. The API that I would expect to see in `BarnBase` would be something like this:

```typescript
// this should be overwritten by subclasses as needed.
protected async defaultBoardingStatus(horse: Horse): Promise<BarnBoardingStatus> {
  return BarnBoardingStatus.CanBoard;
}
async boardingStatus(horse: Horse): Promise<BarnBoardingStatus> {
  const g = await getEdgeTypeInGroup(
    this.viewer,
    this.id,
    horse.id,
    this.getBarnBoardingStatusMap(),
  );
  if (g) {
    return g[0];
  }
  return await this.defaultBoardingStatus(horse);
}
```

**Comment by lolopinto** [comment]
Makes sense. When I was building this, I had viewer stuff in mind. Probably just needs a viewer flag or something to indicate when it's for viewer.

**Comment by Swahvay** [comment]
Wouldn't that just be an Edge to a user table, so you'd pass in the User object (which in your use cases would be the viewer basically)?

**Comment by lolopinto** [comment]
the issue is privacy

if it's friendship status or relationship with a group etc, you don't want to just pass any user's id and get it. you only want it to for the viewer in that case.

ofc, scenarios like this, it's fine

**Comment by Swahvay** [comment]
Hmmm... just throwing things out there, but what if there could be privacy policies attached to edges? A simple `AllowIfViewerIsRule` would handle the relationship case.

**Comment by lolopinto** [comment]
> Hmmm... just throwing things out there, but what if there could be privacy policies attached to edges? A simple `AllowIfViewerIsRule` would handle the relationship case.

hah, just added it here 
https://github.com/lolopinto/ent/pull/598

it's tied to the EdgeQuery not the edge though
