### ISSUE TITLE
add Schema prefix to generated enums

### ISSUE THREAD

**Issue by lolopinto** [lolopinto/ent#609]
almost did it with https://github.com/lolopinto/ent/pull/561 but chose not to

do it automatically for both typescript and graphql.

we need unique names for both GraphQL (GraphQL enforces it) and TS, we import/export all globally.

keep tsType and graphqlType to override if client wants it

**Comment by Swahvay** [comment]
Wow, so many great things fixed last week. Really looking forward to v0.1. Are any of these going to be available on the docker image soon?

**Comment by lolopinto** [comment]
soon!

**Comment by Swahvay** [comment]
![Soon](https://user-images.githubusercontent.com/974639/171269391-33b6e7d5-4e2a-4a02-bc24-6aac0a98de27.jpeg)
