### ISSUE TITLE
Starting with a brand new project fails to run

### ISSUE THREAD

**Issue by mrtom** [lolopinto/ent#628]
I copied the template and ran through the docs from the start.

The issue is a broken import in `src/graphql/index.ts` on line 6.

The generated file has: 
`import schema from "./schema";`

But it should be:

`import schema from "./generated/schema";`

**Comment by lolopinto** [comment]
yah, it's fixed in https://github.com/lolopinto/ent/pull/604 but I haven't created a new image since

**Comment by lolopinto** [comment]
new image and version updated in ent-starter
followed the docs and it worked.
