### ISSUE TITLE
codegen / compile fails if codebase uses global augmentation

### ISSUE THREAD

**Issue by claycoleman** [lolopinto/ent#637]
Hey @lolopinto , love what you've built so far. I recently left FB earlier this year and have been missing the Ent framework ever since 😅 . Got really excited about this project ever since seeing your post in the ex-FB engineering group.

i've been playing around with the project for the past couple days, and so far it's been a dream. recently ran into the issue as described in the title.

no pipe operator in ts/js means I like to add a lot of hack's `Vec\` functions as augmented functions on the `Array` type in ts, so I can do stuff like `await [1,2,3].mapAsync(async ... )` and `[4, null, 6].filterNulls()`. i implement this by using [global augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#global-augmentation), but when trying to compile any ts code that uses these augmented functions, i see errors both when compiling the custom graphql code (where my one callsite is) and when compiling the graphql schema.

i get this working by importing file that both augments the array interface and adds the function implementations to the array prototype. i think we could get this working by just adding a place to add custom requires into the `ts-node` and `ts-node-script` calls that the codegen go file uses.

this issue is definitely a minor convenience feature for the framework lol but thanks for taking a look, and excited to see the framework keep moving forward!

**Comment by lolopinto** [comment]
hey, thanks!

can you provide an example of how you're using this just so I understand what's going on and what's broken?

the concept of global augmentation makes sense but I want to make sure I address the issue correctly.

**Comment by claycoleman** [comment]
sure thing! here's a sample augmentation for the array type:

```
interface Array<T> {
  mapAsync<U>(
    callbackfn: (value: T, index: number, array: readonly T[]) => Promise<U>,
    maxConcurrentPromises?: number | null,
  ): Promise<U[]>;
  ... other augmented functions
}

...
Array.prototype.mapAsync = function arrayAsyncMap(
  callbackfn,
  maxConcurrentPromises = DEFAULT_CONCURRENCY_LIMIT,
) {
  // only null if an explicit null was passed in, so we want to bypass concurrency limits
  if (maxConcurrentPromises == null) {
    return Promise.all(this.map(callbackfn));
  }

  assert(maxConcurrentPromises > 0);
  return asyncPool(maxConcurrentPromises, this, callbackfn);
};
```

in order for this to work, you need to include this file in whatever script you're running (in Ent, in your `src/graphql/index.ts` file) in before you can use any of these functions. 

however, when you run codegen, you get this error:

```
generating graphql code...
/usr/lib/node_modules/ts-node/src/index.ts:692
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/graphql/mutations/upload_post.ts:59:22 - error TS2339: Property 'mapAsync' does not exist on type 'FileUpload[]'.
```

which fatals the codegen

**Comment by lolopinto** [comment]
pre-ent, when there isn't codegen, do you add this to the root/entrypoints of your application so that it's applied everywhere? 

in this case, it looks like it's being used in a custom graphql mutation file based on the `src/graphql/mutations/upload_post.ts` path?

this sounds like something that can be added to options for list of paths to include

**Comment by claycoleman** [comment]
> pre-ent, when there isn't codegen, do you add this to the root/entrypoints of your application so that it's applied everywhere?

yep, usually in the `index.ts` file of an Express app

> in this case, it looks like it's being used in a custom graphql mutation file based on the `src/graphql/mutations/upload_post.ts` path?

yes

> this sounds like something that can be added to options for list of paths to include

sounds great!!
