### ISSUE TITLE
bulkActions not working as anticipated

### ISSUE THREAD

**Issue by claycoleman** [lolopinto/ent#661]
i'm following the mutations i found in `ent-rsvp` `import_guests.ts` in the examples directory of this repo to get an atomic mutation (the equivalent of executing a set of changesets in FB's Ent):

```
let groupAction = CreateGuestGroupAction.create(context.getViewer(), {
        invitationName: row.invitationName,
        eventID,
      }); 
actions.push(groupAction);
actions.push(
        CreateGuestAction.create(context.getViewer(), {
          eventID,
          guestGroupID: groupAction.builder,
          name: row.name,
          emailAddress: row.emailAddress,
        }),
      );


  const action = BaseAction.bulkAction(event, EventBuilder, ...actions);
  return action.saveX();
```

my usage looks like this:

```
    const createPostAction = CreatePostAction.create(context.getViewer(), {
      caption,
    });

    const actions: Action<Ent>[] = [createPostAction];
    succeededUploads.forEach(({ file, bucketKey }) => {
      actions.push(
        CreatePostMediaAction.create(context.getViewer(), {
          postID: createPostAction.builder,
          fileName: file.filename,
          bucketKey: bucketKey,
        }),
      );
    });
   
    // see my note about this below
    const user = await context.getViewer().viewer();

    await BaseAction.bulkAction(user, UserBuilder, ...actions).saveX();
```

However, when running the mutation, I'm getting the error that the required field `PostID` (on the PostMedia entity) is not set. Anything else that I'm supposed to be doing here?

Also, seems like the api for bulk actions requiring an existing ent is a little clunky – there are many create mutations where you might not necessarily have an ent that you can pass through to the `bulkAction` call. (you could use the viewer user, but that kinda defeats the purpose of the logged in privacy policy)

**Comment by lolopinto** [comment]
yah, bulk actions is pretty experimental and hasn't been fleshed out. that not working seems like a bug. i'm changing how things work around there and I'll take a look 

can I assume that your usage is enough to repo (assuming I create the relevant schemas etc).

regarding the existingEnt, yup, that makes sense.

**Comment by claycoleman** [comment]
> can I assume that your usage is enough to repo (assuming I create the relevant schemas etc).

I believe so? you could probably also repro with your example code in `ent-rsvp` that i quoted above, as I followed it when writing mine.

**Comment by lolopinto** [comment]
hmm, can you give me more context as to what's not working?

I tested with a sample schema that looked like yours and it works https://github.com/lolopinto/ent-test1/blob/main/src/main.ts

I assumed it was related to https://github.com/lolopinto/ent/pull/662 but it works in the version prior to that

**Comment by lolopinto** [comment]
closing as old.

Transactions new API now 

https://github.com/lolopinto/ent/issues/1301 exists for adding documentation for that
