### ISSUE TITLE
actionOnlyFields with type: 'Object' won't codegen

### ISSUE THREAD

**Issue by Swahvay** [lolopinto/ent#694]
I have an action on a Schema (`Horse`), with the following definition:

```javascript
{
  operation: ActionOperation.Create,
  actionName: 'AddHorseAction',
  inputName: 'AddHorseInput',
  graphQLName: 'addHorse',
  actionOnlyFields: [
    {
      name: 'info',
      type: 'Object',
      nullable: false,
      actionName: 'CreateHorseInfoAction',
    },
  ],
  fields: ['name', 'nickname'],
}
```

When I run `codegen` I get the following error:

```
we require 1 primary key for each table. schemas had 0
```

If I change it to `nullable: true`, I get a different error:

```
template: action_base.tmpl:33:22: executing "action_base.tmpl" at <useImport $import>: error calling useImport: tried to use export HorseGender at path src/ent/horse/actions/generated/add_horse_action_base.ts even though it was never reserved
```

`HorseGender` is defined on `HorseInfo` as:

```javascript
EnumType({
  name: 'sex',
  values: ['stallion', 'mare', 'gelding'],
  tsType: 'HorseGender',
})
```

`HorseInfo` has this action:

```javascript
{
  operation: ActionOperation.Create,
}
```

**Comment by lolopinto** [comment]
weird. 

not sure what's going on with the 2nd one. 

I recently verified that this was working actually so this is surprising...

what versions are you on?

**Comment by Swahvay** [comment]
v0.0.34, but my docker is pointing to `ghcr.io/lolopinto/ent:0.0.35-nodejs-17-dev`, and I'm running Node 17.0.1.

**Comment by Swahvay** [comment]
![200](https://user-images.githubusercontent.com/974639/151097573-4798f16a-78c0-48c2-9222-a65da903bf14.gif)
