### ISSUE TITLE
Cannot create graphQLType from enums in pattern fields

### ISSUE THREAD

**Issue by Swahvay** [lolopinto/ent#695]
I assume this behaves like a mixin, so every schema that uses the pattern is essentially trying to generate a new type. 🤷‍♂️  Here's the error I get when running `codegen`:

```
enum schema with gqlname HorseConnectionType already exists
enum schema with gqlname Permissions already exists
```

From this definition:
```javascript
EnumType({
  name: 'type',
  values: ['owner', 'trainer', 'rider'],
  tsType: 'HorseConnectionType',
  graphQLType: 'HorseConnectionType',
}),
EnumType({
  name: 'permissions',
  values: ['readOnly', 'manage', 'control'],
}),
```

inside a Pattern being used by two schemas.

**Comment by lolopinto** [comment]
yah, this is dumb and needs to be fixed. will fix when I get back. The field is copied into each schema and it tries to create it for each schema.

**Comment by Swahvay** [comment]
I'm ok if beach pirate parties come before this fix.
