### ISSUE TITLE
Add loadCustomCount method to EntBase objects

### ISSUE THREAD

**Issue by Swahvay** [lolopinto/ent#699]
Would be great to be able to return just a count from a custom load instead of the full Ents.

Example use case:

```javascript
const controllingConnectionsCount = await HorseConnection.loadCustomCount(
  viewer,
  query.And(
    query.Eq('horse_id', horse.id),
    query.Eq('permissions', 'control'),
  ),
);
```

**Comment by lolopinto** [comment]
For now, my suggestion is to use `loadCustomData` and then get the length. It's a similar query which doesn't fetch the ents.

**Comment by Swahvay** [comment]
Does that just load the raw column data? I'll use that, but just out of curiosity, what's a real life use case for this function?

**Comment by Swahvay** [comment]
`loadCustomData` takes a `Context` instead of a `Viewer`. Is there any risk in just passing in `viewer.context` as the second parameter?

**Comment by lolopinto** [comment]
>Does that just load the raw column data? I'll use that, but just out of curiosity, what's a real life use case for this function?

just want the data from the db but don't want to load the ents e.g. don't want privacy checks being run. for example in a script, manually built internal tool etc

**Comment by lolopinto** [comment]
>loadCustomData takes a Context instead of a Viewer. Is there any risk in just passing in viewer.context as the second parameter?

nope. do it.
so it takes an optional `Context` if you want to use [`DataLoader`](https://github.com/graphql/dataloader) etc and avoid double fetching if you make the same query multiple times in the same query

`loadCustom` takes the Viewer because you need that for Privacy checks.
