### ISSUE TITLE
support global edges

### ISSUE THREAD

**Issue by lolopinto** [lolopinto/ent#744]
e.g. to write an edge from external id to internal id

right now we can hack around by just using different type and not validate it

**Comment by Swahvay** [comment]
Is this something that would be needed for a sharded DB?

**Comment by lolopinto** [comment]
>Is this something that would be needed for a sharded DB?

theoretically but would need to figure out the source id. or use a different data format to store it 

e.g. external id mapped to native id on one of the shards
edge from native id to internal id

involves an extra hop 

or use the same logic used for sharding to shard the external id. has its flaws but works.
