### ISSUE TITLE
gencode comment in schema.gql incorrect format, breaks IDE functionality

### ISSUE THREAD

**Issue by rvlasveld** [lolopinto/ent#894]
The generated schema.gql file starts with a comment from gencode, like this:

```
// Generated by github.com/lolopinto/ent/ent, DO NOT EDIT.
```

This comment format is incorrect for GraphQL, and breaks IDE features such as "Go To Definition" on types. 

GraphQL comments, that are not exported, should start with a `#`. See https://spec.graphql.org/June2018/#sec-Comments. 

(I believe that this is generated by this line, but I'm not sure; haven't had time to try to fix this locally and put up a PR: https://github.com/lolopinto/ent/blob/a74f06eb6d63a0a5b175f090617002caca719f20/internal/graphql/generate_schema.tmpl#L9)

**Comment by lolopinto** [comment]
sure, can fix. what IDE are you using that you have this functionality?

**Comment by rvlasveld** [comment]
I'm using VSCode and this extension, which I believe is the most popular:
https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql.

Many thanks!
